name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag awsps
    - name: Copy spago
      run: |
        id=$(docker create awsps)
        docker cp $id:/root/.local/bin/spago - > spago
        docker rm -v $id
    - name: Copy purs
      run: |
        id=$(docker create awsps)
        docker cp $id:/root/.local/bin/purs - > purs
        docker rm -v $id
    - uses: actions/upload-artifact@v2
      with:
        name: spago-u1604
        path: spago
    - uses: actions/upload-artifact@v2
      with:
        name: purs-u1604
        path: purs